/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oHGfeh1stos
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import Link from "next/link";


export function ProjectsGallery() {
  const [activeFilter, setActiveFilter] = useState("all");
  const projects = [
    {
      id: 1,
      image: "/placeholder.svg",
      name: "Luxury Bathroom Remodel",
      type: "Bathroom remodel",
    },
    {
      id: 2,
      image: "/placeholder.svg",
      name: "Modern Custom Home",
      type: "Custom home",
    },
    {
      id: 3,
      image: "/placeholder.svg",
      name: "Gourmet Kitchen Renovation",
      type: "Kitchen remodel",
    },
    {
      id: 4,
      image: "/placeholder.svg",
      name: "Cozy Living Room Addition",
      type: "Living utility",
    },
    {
      id: 5,
      image: "/placeholder.svg",
      name: "Spacious Home Extension",
      type: "Home addition",
    },
    {
      id: 6,
      image: "/placeholder.svg",
      name: "Elegant Bathroom Upgrade",
      type: "Bathroom remodel",
    },
  ];
  const filteredProjects =
    activeFilter === "all"
      ? projects
      : projects.filter(
          (project) => project.type.toLowerCase() === activeFilter
        );
  return (
    <div className=" mx-auto py-8 md:py-12">
      <div className="flex justify-between items-center mb-6 md:mb-8">
        <div className="flex gap-2 flex-wrap">
          <Button
            variant={activeFilter === "all" ? "primary" : "outline"}
            onClick={() => setActiveFilter("all")}
          >
            All
          </Button>
          <Button
            variant={
              activeFilter === "bathroom remodel" ? "primary" : "outline"
            }
            onClick={() => setActiveFilter("bathroom remodel")}
          >
            Bathroom remodels
          </Button>
          <Button
            variant={activeFilter === "custom home" ? "primary" : "outline"}
            onClick={() => setActiveFilter("custom home")}
          >
            Custom homes
          </Button>
          <Button
            variant={activeFilter === "kitchen remodel" ? "primary" : "outline"}
            onClick={() => setActiveFilter("kitchen remodel")}
          >
            Kitchen remodels
          </Button>
          <Button
            variant={activeFilter === "living utility" ? "primary" : "outline"}
            onClick={() => setActiveFilter("living utility")}
          >
            Living utility
          </Button>
          <Button
            variant={activeFilter === "home addition" ? "primary" : "outline"}
            onClick={() => setActiveFilter("home addition")}
          >
            Home additions
          </Button>
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {filteredProjects.map((project) => (
          <Link
            key={project.id}
            href="/"
            className="relative overflow-hidden group"
            style={{
              borderImage:
                "linear-gradient(hsl(240 100% 20% / 0.6), hsl(0 100% 20% / 0.6)) fill 1",
            }}
          >
            <Image
              src="https://images.squarespace-cdn.com/content/v1/64025cbc903531470f0036d6/5adaf197-109b-4c7d-a610-39cff63616c7/8.JPG?format=2500w"
              alt={project.name}
              width={600}
              height={400}
              className="w-full aspect-[2/3] object-cover transition-transform duration-500 ease-in-out group-hover:scale-105"
            />
            <div className="absolute inset-x-0 bottom-0 p-3 text-white transition-colors">
              <h3 className="text-lg font-semibold">{project.name}</h3>
              <p className="text-sm">{project.type}</p>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}
