/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oHGfeh1stos
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import Link from "next/link";
import { urlFor } from "@/src/app/lib/urlFor";

export function ProjectsGallery(props) {
  const { projects } = props;
  const [activeFilter, setActiveFilter] = useState("all");

  // Map Sanity project types to filter button values
  const typeMapping = {
    "bathroom remodel": "bathroomRemodel",
    "custom home": "customHomeBuild",
    "kitchen remodel": "kitchenRemodel",
    "living utility": "customProjects",
    "home addition": "addition"
  };

  // Filter projects based on active filter
  const filteredProjects = projects.filter(project => {
    if (activeFilter === "all") return true;
    return project.type === typeMapping[activeFilter];
  });

  return (
    <div className="py-8 mx-auto md:py-12">
      <div className="flex items-center justify-between mb-6 md:mb-8">
        <div className="flex flex-wrap gap-2">
          <Button
            variant={activeFilter === "all" ? "primary" : "outline"}
            onClick={() => setActiveFilter("all")}
          >
            All
          </Button>
          <Button
            variant={activeFilter === "bathroom remodel" ? "primary" : "outline"}
            onClick={() => setActiveFilter("bathroom remodel")}
          >
            Bathroom remodels
          </Button>
          <Button
            variant={activeFilter === "custom home" ? "primary" : "outline"}
            onClick={() => setActiveFilter("custom home")}
          >
            Custom homes
          </Button>
          <Button
            variant={activeFilter === "kitchen remodel" ? "primary" : "outline"}
            onClick={() => setActiveFilter("kitchen remodel")}
          >
            Kitchen remodels
          </Button>
          <Button
            variant={activeFilter === "living utility" ? "primary" : "outline"}
            onClick={() => setActiveFilter("living utility")}
          >
            Living utility
          </Button>
          <Button
            variant={activeFilter === "home addition" ? "primary" : "outline"}
            onClick={() => setActiveFilter("home addition")}
          >
            Home additions
          </Button>
        </div>
      </div>
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
        {filteredProjects.map((project) => (
          <Link
            key={project._id}
            href={project.slug}
            className="relative overflow-hidden group"
            style={{
              borderImage:
                "linear-gradient(hsl(240 100% 20% / 0.6), hsl(0 100% 20% / 0.6)) fill 1",
            }}
          >
            <Image
              quality={100}
              src={urlFor(project.mainImage).url()}
              alt={project.title}
              width={900}
              height={400}
              className="w-full aspect-[2/3] object-cover transition-transform duration-500 ease-in-out group-hover:scale-105"
            />
            <div className="absolute inset-x-0 bottom-0 p-3 text-white transition-colors">
              <h3 className="text-lg font-semibold">{project.title}</h3>
              <p className="text-sm capitalize">{project.type}</p>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}
